"""Base Omoda / Jaecoo entity: hookup to the coordinator + shared device_info.

entity_id continuity (PHASE 3d): so as not to lose recorder/dashboard history at
the cutover from the bridge, each entity FORCES its own `entity_id` instead of
letting it derive implicitly. The default object_id = slugify(name) — which reproduces
EXACTLY the `omoda_jaecoo_*` ids already generated by the bridge (has_entity_name=False →
HA slugifies just the name). Where the bridge uses an id not derivable from the name
(e.g. the command buttons = `omoda_jaecoo_<key>`) an explicit `object_id` is passed.
"""
from __future__ import annotations

from typing import Any

from homeassistant.exceptions import HomeAssistantError
from homeassistant.helpers.entity import DeviceInfo
from homeassistant.helpers.update_coordinator import CoordinatorEntity
from homeassistant.util import slugify

from .const import DEFAULT_VEHICLE_NAME, DOMAIN
from .coordinator import OmodaJaecooCoordinator


def field_on(v) -> bool | None:
    """Interpret a 5A02 field as on/open (True), off/closed (False)
    or ABSENT (None).

    `None` / `"None"` / `""` = field absent → returns `None`, so at the entity level
    the restored value (or `unknown`) surfaces instead of a false `False`. Otherwise
    true if nonzero, with a NUMERIC comparison when possible (`"0.0"` = off,
    aligned across binary_sensor/lock/switch/cover); textual fallback for booleans."""
    if v is None:
        return None
    s = str(v).strip()
    if s in ("", "None"):
        return None
    try:
        return float(s) != 0.0
    except (TypeError, ValueError):
        return s.lower() not in ("false", "off", "no")


def get_rt_field(rt: dict, field: str) -> Any:
    """Look up a field in the realtime dict, checking both the root and nested objects."""
    if not isinstance(rt, dict):
        return None
    if field in rt:
        return rt[field]
    for k, v in rt.items():
        if isinstance(v, dict):
            if field in v:
                return v[field]
    return None


class OmodaJaecooEntity(CoordinatorEntity[OmodaJaecooCoordinator]):
    """Base entity: single device 'Omoda / Jaecoo' identified by the VIN."""

    # has_entity_name=True + translation_key → the entity NAME is TRANSLATED (it/en) and HA
    # prepends it to the device → "Omoda / Jaecoo Battery" / "Jaecoo 7 Battery". The entity_id keeps the
    # bridge style "omoda_jaecoo_*" (set explicitly below, from `name`/`object_id`) → history intact.
    _attr_has_entity_name = True

    def __init__(
        self,
        coordinator: OmodaJaecooCoordinator,
        name: str,
        unique_suffix: str,
        *,
        object_id: str | None = None,
        entity_id_format: str | None = None,
    ) -> None:
        super().__init__(coordinator)
        # `name` is NO longer the friendly name (translation_key provides it): we keep it only to
        # compute the object_id of the entity_id and for logs. Do NOT set _attr_name, otherwise
        # it would win over the translation_key.
        self._raw_name = name
        self._attr_unique_id = f"{coordinator.vin}_{unique_suffix}"
        oid = object_id or slugify(name)          # e.g. "omoda_jaecoo_batteria"
        # translation_key = object_id without the domain prefix → key in translations/*.json
        self._attr_translation_key = oid[len(DOMAIN) + 1:] if oid.startswith(f"{DOMAIN}_") else oid
        # EXPLICIT entity_id = continuity with the bridge (default = slugify(name)).
        if entity_id_format:
            self.entity_id = entity_id_format.format(oid)
        # dynamic device: the name reflects the real vehicle (Omoda / Jaecoo, Jaecoo 7…), read
        # from the coordinator (nickname/model from queryList, or manual override). The device is
        # identified by the VIN → renaming it does NOT touch entity_id or history.
        self._attr_device_info = DeviceInfo(
            identifiers={(DOMAIN, coordinator.vin)},
            name=coordinator.vehicle_name or DEFAULT_VEHICLE_NAME,
            manufacturer=coordinator.vehicle_brand or "Omoda",
            model=coordinator.vehicle_model or None,
        )


class OmodaJaecooOptimisticMixin:
    """Optimistic state for the actuators (lock/switch/cover).

    A command ACTUATES on the car immediately, but the real state comes back ONLY via MQTT
    when the car is awake: the last "live" value can stay frozen for hours. After an action
    we immediately show the target state (optimistic) and keep it until a NEW message
    arrives from the car (`last_seen` advances), which becomes the truth.
    To be used as the FIRST base class (precedes OmodaJaecooEntity in the MRO)."""

    _opt_value = None
    _opt_anchor = None

    def _set_optimistic(self, value) -> None:
        self._opt_value = value
        self._opt_anchor = self.coordinator.data.get("last_seen")
        self.async_write_ha_state()

    def _clear_optimistic(self) -> None:
        self._opt_value = None
        self._opt_anchor = None

    async def _run_command(self, key: str, target, params: dict | None = None) -> None:
        """Actuate a command, immediately showing the target state (optimistic).

        `params` = parametric override of the body (climate: temperature/duration; scheduled
        charging: plan). On a command exception (network/auth/backend) it CANCELS
        the optimism — so the card returns to the real state instead of staying stuck
        on a target that was never actuated — and propagates a readable error (toast in UI).

        The car runs ONE command at a time: commands are serialized inside the coordinator
        (a queue), so a second one WAITS its turn instead of erroring."""
        self._set_optimistic(target)
        try:
            await self.coordinator.async_send_command(key, params)
        except Exception as err:  # noqa: BLE001 — any command failure
            self._clear_optimistic()
            self.async_write_ha_state()
            raise HomeAssistantError(f"Command «{key}» failed: {err}") from err

    def _handle_coordinator_update(self) -> None:
        # a new message from the car (last_seen changed) invalidates the optimism
        if self._opt_value is not None and \
                self.coordinator.data.get("last_seen") != self._opt_anchor:
            self._clear_optimistic()
        super()._handle_coordinator_update()
